// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo.proto

package v1

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Todo struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Todo) Reset()         { *m = Todo{} }
func (m *Todo) String() string { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()    {}
func (*Todo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{0}
}

func (m *Todo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Todo.Unmarshal(m, b)
}
func (m *Todo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Todo.Marshal(b, m, deterministic)
}
func (m *Todo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Todo.Merge(m, src)
}
func (m *Todo) XXX_Size() int {
	return xxx_messageInfo_Todo.Size(m)
}
func (m *Todo) XXX_DiscardUnknown() {
	xxx_messageInfo_Todo.DiscardUnknown(m)
}

var xxx_messageInfo_Todo proto.InternalMessageInfo

func (m *Todo) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Todo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func init() {
	proto.RegisterType((*Todo)(nil), "v1.Todo")
}

func init() { proto.RegisterFile("todo.proto", fileDescriptor_0e4b95d0c4e09639) }

var fileDescriptor_0e4b95d0c4e09639 = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xc9, 0x4f, 0xc9,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x33, 0x94, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0x83, 0x88, 0x28, 0x19, 0x70, 0xb1, 0x84, 0xe4, 0xa7, 0xe4, 0x0b, 0x09, 0x71, 0xb1,
	0x24, 0xe5, 0xa7, 0x54, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x22, 0x5c,
	0xac, 0x25, 0x99, 0x25, 0x39, 0xa9, 0x12, 0x4c, 0x60, 0x41, 0x08, 0xc7, 0x48, 0x8f, 0x8b, 0x1b,
	0xa4, 0x23, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0x48, 0x9e, 0x8b, 0x25, 0x20, 0xbf, 0xb8,
	0x44, 0x88, 0x43, 0xaf, 0xcc, 0x50, 0x0f, 0x24, 0x21, 0xc5, 0x09, 0x62, 0xb9, 0xe6, 0x16, 0x94,
	0x54, 0x2a, 0x31, 0x68, 0x30, 0x26, 0xb1, 0x81, 0x2d, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x7b, 0x80, 0x2d, 0x19, 0x88, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TodoServiceClient is the client API for TodoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TodoServiceClient interface {
	Post(ctx context.Context, opts ...grpc.CallOption) (TodoService_PostClient, error)
}

type todoServiceClient struct {
	cc *grpc.ClientConn
}

func NewTodoServiceClient(cc *grpc.ClientConn) TodoServiceClient {
	return &todoServiceClient{cc}
}

func (c *todoServiceClient) Post(ctx context.Context, opts ...grpc.CallOption) (TodoService_PostClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TodoService_serviceDesc.Streams[0], "/v1.TodoService/Post", opts...)
	if err != nil {
		return nil, err
	}
	x := &todoServicePostClient{stream}
	return x, nil
}

type TodoService_PostClient interface {
	Send(*Todo) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type todoServicePostClient struct {
	grpc.ClientStream
}

func (x *todoServicePostClient) Send(m *Todo) error {
	return x.ClientStream.SendMsg(m)
}

func (x *todoServicePostClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TodoServiceServer is the server API for TodoService service.
type TodoServiceServer interface {
	Post(TodoService_PostServer) error
}

func RegisterTodoServiceServer(s *grpc.Server, srv TodoServiceServer) {
	s.RegisterService(&_TodoService_serviceDesc, srv)
}

func _TodoService_Post_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TodoServiceServer).Post(&todoServicePostServer{stream})
}

type TodoService_PostServer interface {
	SendAndClose(*Empty) error
	Recv() (*Todo, error)
	grpc.ServerStream
}

type todoServicePostServer struct {
	grpc.ServerStream
}

func (x *todoServicePostServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *todoServicePostServer) Recv() (*Todo, error) {
	m := new(Todo)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _TodoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.TodoService",
	HandlerType: (*TodoServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Post",
			Handler:       _TodoService_Post_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "todo.proto",
}
